# Copyright Contributors to the Open Cluster Management project
{{ if .Values.plugin }}
apiVersion: console.openshift.io/v1alpha1
kind: ConsolePlugin
metadata:
  name: acm-console-plugin
spec:
  displayName: Red Hat Advanced Cluster Management
  proxy:
    services:
      - authorize: true
        name: {{ template "console.fullname" . }}-console-v2
        namespace: {{ .Release.Namespace }}
        port: 3000
  service:
    basePath: /plugin/
    name: {{ template "console.fullname" . }}-console-v2
    namespace: {{ .Release.Namespace }}
    port: 3000
{{ end }}